sudo: required
services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/osrm-backend-hamburg .

script:
  - docker run $DOCKER_ID/osrm-backend-hamburg /usr/local/bin/osrm-routed --version

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/osrm-backend-hamburg
