sudo: required
services:
  - docker

before_install:
  - docker build -t klonikt/osrm-backend-hamburg .

script:
  - docker run klonikt/osrm-backend-hamburg /usr/local/bin/osrm-routed --version

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push klonikt/osrm-backend-hamburg
