sudo: required
services:
  - docker

before_install:
  - docker build -t klonikt/osrm-backend-docker-hamburg .

script:
  - docker run klonikt/osrm-backend-docker-hamburg /usr/local/bin/osrm-routed --version

